
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 25 22:34:01 CET 2026
//----------------------------------------------------

import java_cup.runtime.*;
import java.io.*;

/** CUP v0.10k generated parser.
  * @version Sun Jan 25 22:34:01 CET 2026
  */
public class MPParserError extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public MPParserError() {super();}

  /** Constructor which sets the default scanner. */
  public MPParserError(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\045\000\002\003\005\000\002\002\004\000\002\003" +
    "\005\000\002\003\004\000\002\004\004\000\002\005\004" +
    "\000\002\005\003\000\002\006\005\000\002\006\005\000" +
    "\002\006\004\000\002\007\003\000\002\007\003\000\002" +
    "\007\003\000\002\010\005\000\002\010\003\000\002\010" +
    "\005\000\002\011\003\000\002\011\003\000\002\012\005" +
    "\000\002\012\005\000\002\012\004\000\002\013\005\000" +
    "\002\013\005\000\002\013\003\000\002\014\003\000\002" +
    "\014\003\000\002\015\012\000\002\015\012\000\002\015" +
    "\011\000\002\015\010\000\002\015\006\000\002\015\005" +
    "\000\002\015\004\000\002\016\005\000\002\016\003\000" +
    "\002\016\005\000\002\016\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\071\000\004\004\005\001\002\000\004\002\073\001" +
    "\002\000\012\003\010\006\015\007\014\010\012\001\002" +
    "\000\014\006\ufffb\007\ufffb\010\ufffb\011\ufffb\014\ufffb\001" +
    "\002\000\006\003\070\014\067\001\002\000\004\002\ufffe" +
    "\001\002\000\006\003\065\005\066\001\002\000\006\003" +
    "\ufff5\014\ufff5\001\002\000\014\006\015\007\014\010\012" +
    "\011\017\014\022\001\002\000\006\003\ufff6\014\ufff6\001" +
    "\002\000\006\003\ufff7\014\ufff7\001\002\000\010\003\ufff1" +
    "\005\ufff1\021\ufff1\001\002\000\006\003\044\014\043\001" +
    "\002\000\014\006\ufffc\007\ufffc\010\ufffc\011\ufffc\014\ufffc" +
    "\001\002\000\010\003\ufff3\005\ufff3\021\ufff3\001\002\000" +
    "\006\003\030\020\031\001\002\000\010\003\ufffd\005\ufffd" +
    "\021\025\001\002\000\010\003\ufff0\005\ufff0\021\ufff0\001" +
    "\002\000\010\003\026\011\017\014\022\001\002\000\010" +
    "\003\ufff2\005\ufff2\021\ufff2\001\002\000\010\003\ufff4\005" +
    "\ufff4\021\ufff4\001\002\000\010\003\uffed\005\uffed\021\uffed" +
    "\001\002\000\010\003\034\014\032\015\033\001\002\000" +
    "\014\003\uffe8\005\uffe8\016\uffe8\017\uffe8\021\uffe8\001\002" +
    "\000\014\003\uffe9\005\uffe9\016\uffe9\017\uffe9\021\uffe9\001" +
    "\002\000\010\003\uffee\005\uffee\021\uffee\001\002\000\014" +
    "\003\uffea\005\uffea\016\uffea\017\uffea\021\uffea\001\002\000" +
    "\014\003\uffef\005\uffef\016\037\017\040\021\uffef\001\002" +
    "\000\006\014\032\015\033\001\002\000\006\014\032\015" +
    "\033\001\002\000\014\003\uffeb\005\uffeb\016\uffeb\017\uffeb" +
    "\021\uffeb\001\002\000\014\003\uffec\005\uffec\016\uffec\017" +
    "\uffec\021\uffec\001\002\000\006\003\046\012\045\001\002" +
    "\000\010\003\uffe1\005\uffe1\021\uffe1\001\002\000\006\003" +
    "\047\023\050\001\002\000\010\003\uffe2\005\uffe2\021\uffe2" +
    "\001\002\000\010\003\uffe3\005\uffe3\021\uffe3\001\002\000" +
    "\004\014\051\001\002\000\010\003\uffdf\022\uffdf\024\uffdf" +
    "\001\002\000\010\003\054\022\053\024\055\001\002\000" +
    "\006\003\064\014\063\001\002\000\012\003\uffe4\005\uffe4" +
    "\014\062\021\uffe4\001\002\000\006\003\057\013\056\001" +
    "\002\000\010\003\060\011\017\014\022\001\002\000\010" +
    "\003\uffe5\005\uffe5\021\uffe5\001\002\000\010\003\uffe6\005" +
    "\uffe6\021\uffe6\001\002\000\010\003\uffe7\005\uffe7\021\uffe7" +
    "\001\002\000\010\003\uffdd\022\uffdd\024\uffdd\001\002\000" +
    "\010\003\uffe0\022\uffe0\024\uffe0\001\002\000\010\003\uffde" +
    "\022\uffde\024\uffde\001\002\000\004\002\uffff\001\002\000" +
    "\004\002\001\001\002\000\006\003\072\021\071\001\002" +
    "\000\014\006\ufff8\007\ufff8\010\ufff8\011\ufff8\014\ufff8\001" +
    "\002\000\014\006\ufffa\007\ufffa\010\ufffa\011\ufffa\014\ufffa" +
    "\001\002\000\014\006\ufff9\007\ufff9\010\ufff9\011\ufff9\014" +
    "\ufff9\001\002\000\004\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\071\000\004\003\003\001\001\000\002\001\001\000" +
    "\012\004\010\005\012\006\005\007\006\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\016\006\017\007\006\010\022" +
    "\011\020\012\015\015\023\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\011\026\012\015\015\023" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\013\035\014\034\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\014\041\001\001\000\004\014\040" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\016\051\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\011\060\012\015\015\023\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$MPParserError$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$MPParserError$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$MPParserError$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public int errNo = 0;

    public static void main(String[] args) {
        try {
            FileReader file = new FileReader(args[0]);
            MPLexer scanner = new MPLexer(file);
            MPParserError parser = new MPParserError(scanner);
            parser.parse();
            if (parser.errNo == 0)
                System.out.println("Analiza zavrsena. U kodu nema gresaka.");
            else
                System.out.println("Analiza zavrsena. Broj gresaka: " + parser.errNo);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void syntax_error(Symbol cur_token) {
       
    }

    public void report_error(String message, Object info) {
        System.out.print( message );
    }

    public int getLine() {
        return ((MPLexer)getScanner()).getLine();
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$MPParserError$actions {
  private final MPParserError parser;

  /** Constructor */
  CUP$MPParserError$actions(MPParserError parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$MPParserError$do_action(
    int                        CUP$MPParserError$act_num,
    java_cup.runtime.lr_parser CUP$MPParserError$parser,
    java.util.Stack            CUP$MPParserError$stack,
    int                        CUP$MPParserError$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$MPParserError$result;

      /* select the action based on the action number */
      switch (CUP$MPParserError$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // NameList ::= NameList error ID 
            {
              Object RESULT = null;
		
               System.out.println("Greska u liniji " + parser.getLine() + " Nedostaje ',' izmedju identifikatora");
               parser.errNo++;
           
              CUP$MPParserError$result = new java_cup.runtime.Symbol(12/*NameList*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // NameList ::= NameList COMMA error 
            {
              Object RESULT = null;
		
               System.out.println("Greska u liniji " + parser.getLine() + " Nedostaje identifikator posle ','");
               parser.errNo++;
           
              CUP$MPParserError$result = new java_cup.runtime.Symbol(12/*NameList*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // NameList ::= ID 
            {
              Object RESULT = null;

              CUP$MPParserError$result = new java_cup.runtime.Symbol(12/*NameList*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // NameList ::= NameList COMMA ID 
            {
              Object RESULT = null;

              CUP$MPParserError$result = new java_cup.runtime.Symbol(12/*NameList*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // ApplyExpression ::= FOR error 
            {
              Object RESULT = null;
		
                    System.out.println("Greska u liniji " + parser.getLine() + " Nedostaje identifikator posle 'FOR'");
                    parser.errNo++;
                
              CUP$MPParserError$result = new java_cup.runtime.Symbol(11/*ApplyExpression*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // ApplyExpression ::= FOR ID error 
            {
              Object RESULT = null;
		
                    System.out.println("Greska u liniji " + parser.getLine() + " Nedostaje 'IN'");
                    parser.errNo++;
                
              CUP$MPParserError$result = new java_cup.runtime.Symbol(11/*ApplyExpression*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // ApplyExpression ::= FOR ID IN error 
            {
              Object RESULT = null;
		
                    System.out.println("Greska u liniji " + parser.getLine() + " Nedostaje '['");
                    parser.errNo++;
                
              CUP$MPParserError$result = new java_cup.runtime.Symbol(11/*ApplyExpression*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // ApplyExpression ::= FOR ID IN LBRACKET NameList error 
            {
              Object RESULT = null;
		
                    System.out.println("Greska u liniji " + parser.getLine() + " Nedostaje ']'");
                    parser.errNo++;
                
              CUP$MPParserError$result = new java_cup.runtime.Symbol(11/*ApplyExpression*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-5)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // ApplyExpression ::= FOR ID IN LBRACKET NameList RBRACKET error 
            {
              Object RESULT = null;
		
                    System.out.println("Greska u liniji " + parser.getLine() + " Nedostaje 'APPLY' i izraz");
                    parser.errNo++;
                
              CUP$MPParserError$result = new java_cup.runtime.Symbol(11/*ApplyExpression*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-6)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // ApplyExpression ::= FOR ID IN LBRACKET NameList RBRACKET APPLY error 
            {
              Object RESULT = null;
		
                    System.out.println("Greska u liniji " + parser.getLine() + " Nedostaje izraz posle 'APPLY'");
                    parser.errNo++;
                
              CUP$MPParserError$result = new java_cup.runtime.Symbol(11/*ApplyExpression*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-7)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // ApplyExpression ::= FOR ID IN LBRACKET NameList RBRACKET APPLY Expression 
            {
              Object RESULT = null;

              CUP$MPParserError$result = new java_cup.runtime.Symbol(11/*ApplyExpression*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-7)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // TermExpression ::= ID 
            {
              Object RESULT = null;

              CUP$MPParserError$result = new java_cup.runtime.Symbol(10/*TermExpression*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // TermExpression ::= CONST 
            {
              Object RESULT = null;

              CUP$MPParserError$result = new java_cup.runtime.Symbol(10/*TermExpression*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // ArithmeticExpression ::= TermExpression 
            {
              Object RESULT = null;

              CUP$MPParserError$result = new java_cup.runtime.Symbol(9/*ArithmeticExpression*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // ArithmeticExpression ::= ArithmeticExpression MINUS TermExpression 
            {
              Object RESULT = null;

              CUP$MPParserError$result = new java_cup.runtime.Symbol(9/*ArithmeticExpression*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // ArithmeticExpression ::= ArithmeticExpression PLUS TermExpression 
            {
              Object RESULT = null;

              CUP$MPParserError$result = new java_cup.runtime.Symbol(9/*ArithmeticExpression*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // Assignment ::= ID error 
            {
              Object RESULT = null;
		
                  System.out.println("Greska u liniji " + parser.getLine() +  "Nedostaje ':=' u dodeli");
                  parser.errNo++;
             
              CUP$MPParserError$result = new java_cup.runtime.Symbol(8/*Assignment*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // Assignment ::= ID ASSIGN error 
            {
              Object RESULT = null;
		
                  System.out.println("Greska u liniji " + parser.getLine() + " Neispravan izraz u dodeli");
                  parser.errNo++;
             
              CUP$MPParserError$result = new java_cup.runtime.Symbol(8/*Assignment*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // Assignment ::= ID ASSIGN ArithmeticExpression 
            {
              Object RESULT = null;

              CUP$MPParserError$result = new java_cup.runtime.Symbol(8/*Assignment*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // Expression ::= ApplyExpression 
            {
              Object RESULT = null;

              CUP$MPParserError$result = new java_cup.runtime.Symbol(7/*Expression*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // Expression ::= Assignment 
            {
              Object RESULT = null;

              CUP$MPParserError$result = new java_cup.runtime.Symbol(7/*Expression*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // Expressions ::= Expressions SEMICOLON error 
            {
              Object RESULT = null;
		
                  System.out.println("Greska u liniji " + parser.getLine() + " Nedostaje izraz nakon ';'");
                  parser.errNo++;
              
              CUP$MPParserError$result = new java_cup.runtime.Symbol(6/*Expressions*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // Expressions ::= Expression 
            {
              Object RESULT = null;

              CUP$MPParserError$result = new java_cup.runtime.Symbol(6/*Expressions*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // Expressions ::= Expressions SEMICOLON Expression 
            {
              Object RESULT = null;

              CUP$MPParserError$result = new java_cup.runtime.Symbol(6/*Expressions*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // Type ::= BOOL 
            {
              Object RESULT = null;

              CUP$MPParserError$result = new java_cup.runtime.Symbol(5/*Type*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // Type ::= FLOAT 
            {
              Object RESULT = null;

              CUP$MPParserError$result = new java_cup.runtime.Symbol(5/*Type*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // Type ::= INT 
            {
              Object RESULT = null;

              CUP$MPParserError$result = new java_cup.runtime.Symbol(5/*Type*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // Declaration ::= Type error 
            {
              Object RESULT = null;
		
                  System.out.println("Greska u liniji " + parser.getLine() + " Neispravan ID u deklaraciji");
                  parser.errNo++;
              
              CUP$MPParserError$result = new java_cup.runtime.Symbol(4/*Declaration*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // Declaration ::= Type ID error 
            {
              Object RESULT = null;
		
                  System.out.println("Greska u liniji " + parser.getLine() + " Nedostaje ';' nakon deklaracije");
                  parser.errNo++;
              
              CUP$MPParserError$result = new java_cup.runtime.Symbol(4/*Declaration*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // Declaration ::= Type ID SEMICOLON 
            {
              Object RESULT = null;

              CUP$MPParserError$result = new java_cup.runtime.Symbol(4/*Declaration*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // Declarations ::= Declaration 
            {
              Object RESULT = null;

              CUP$MPParserError$result = new java_cup.runtime.Symbol(3/*Declarations*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // Declarations ::= Declarations Declaration 
            {
              Object RESULT = null;

              CUP$MPParserError$result = new java_cup.runtime.Symbol(3/*Declarations*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Block ::= Declarations Expressions 
            {
              Object RESULT = null;
		 
    	System.out.println("Redukcija po smeni 2."); 
    
              CUP$MPParserError$result = new java_cup.runtime.Symbol(2/*Block*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // Program ::= MAIN error 
            {
              Object RESULT = null;
		
            System.out.println("Greska u liniji  " + parser.getLine() + "Telo programa je nekorektno.");
            parser.errNo++;
        
              CUP$MPParserError$result = new java_cup.runtime.Symbol(1/*Program*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // Program ::= MAIN Block error 
            {
              Object RESULT = null;
		
            System.out.println("Nedostaje 'exit' na kraju programa");
            parser.errNo++;
        
              CUP$MPParserError$result = new java_cup.runtime.Symbol(1/*Program*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= Program EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-1)).value;
		RESULT = start_val;
              CUP$MPParserError$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$MPParserError$parser.done_parsing();
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // Program ::= MAIN Block EXIT 
            {
              Object RESULT = null;
		 
    	System.out.println("Redukcija po smeni 1."); 
    
              CUP$MPParserError$result = new java_cup.runtime.Symbol(1/*Program*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

